include $(PWD)/steam_rules

CFLAGS	:= -O3 -DCPP_MEMORY -Wall -I/usr/local/include -I$(PWD)/../sources -D__LINUX_ALSA__ -D__LINUX_ALSASEQ__ -D_DEBUG
 
CXXFLAGS:= $(CFLAGS)

EXTENSION:= steam-exe

LIBS	:=  -O3 -L/local/lib -Wl,-rpath,/usr/local/lib -lasound -lSDL -ljack -lpthread
