-include $(PWD)/rules_base

TARGET=lgpt

export OBJS:=$(OFILES)

TARGET = lgpt-psp

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = LittleGPTracker
PSP_EBOOT_ICON = $(PWD)/psp_icon.png
PSP_EBOOT_PIC1 = $(PWD)/psp_bg.png

PSPSDK=$(shell $(PSPDEV)/bin/psp-config --pspsdk-path)
PSPBIN = $(PSPSDK)/../bin

CFLAGS	:=	-O3 -G0 -Wall -DPLATFORM_$(PLATFORM) -DNDEBUG -DCPP_MEMORY -I$(PWD)/../sources -I$(PSPSDK)/include

CXXFLAGS:=	$(CFLAGS) -fexceptions -fno-rtti

EXTENSION:= elf

LIBS = -L$(PSPDEV)/psp/lib -lSDL_image -lpng -lz -lstdc++ -lSDL -lGL -lGLU -lglut -lm -lc -ljpeg
LIBS += -lpspvfpu -lpspgu -lpsphprm -lpsprtc -lpspaudio -lpspirkeyb -lpsppower
