-include $(PWD)/rules_base

%.app: $(OFILES)
	$(CXX) $(LDFLAGS) -arch i386 -framework SDL -framework Cocoa -framework Carbon -o $@ $(OFILES) $(LIBS)
	mv $@ ../lgpt

CFLAGS	:= -O3 -Wall -I$(PWD) -I/Library/Frameworks/SDL.framework/Headers 

CXXFLAGS:= $(CFLAGS)

EXTENSION:= app

LIBS	:=  

