-include $(PWD)/rules_base
STRIP = arm-linux-strip

%.gpe: $(OFILES)
	$(CXX) -static $(LDFLAGS) -o $@ $(OFILES) $(LIBS)
	@$(STRIP) $@

DEVKITARM=/c/devkitGP2X

DEVKITPRO=$(DEVKITARM)/..

TOOLPATH=$(DEVKITARM)/bin
PREFIX		:=	arm-linux-
SDL_BASE = C:/devkitGP2X/bin/arm-linux-

CFLAGS	:=	`$(SDL_BASE)sdl-config --cflags` -DNDEBUG -O2 -Wall -DCPP_MEMORY -DPLATFORM_$(PLATFORM) -I$(PWD)/../sources -D__LINUX_OSS__ 

CXXFLAGS:=	$(CFLAGS)

EXTENSION:= gpe

LIBS	:=  -L$(PWD)/../libs/GP2XSDL/ -lSDL -lpthread 


LIBDIRS	:=	$(DEKVITPRO)/lib
